#!/usr/bin/env node
var spawn = require('child_process').spawn;
var args = require('minimist')(process.argv);

var dir = args.dir || args.d || __dirname;

console.log('Serving dir: '+dir);

var app = require('express')();

var fs = require('fs');

function convert(avi, mp4, callback) {
  var ffmpeg = spawn('ffmpeg', [
    '-i', avi,
    '-f', 'mp4',
    mp4
  ])

  ffmpeg.stderr.on('data', function(buf) {
    console.log(buf.toString());
  });
  
  ffmpeg.on('exit', function() {
    callback();
  })
}


app.get('/movies/:basename.:ext', function(req, res) {
  var avi = dir+"/"+req.params.basename+".avi"
  var mp4 = dir+"/"+req.params.basename+".mp4"
  if (req.params.ext === 'avi') {
    if (fs.existsSync(avi)) {
      if (fs.existsSync(mp4)) {
        console.log('exists, sending');
        res.sendFile(mp4);
      } else {
        console.log('converting');
        convert(avi, mp4, function(err) {
          console.log('done, sending');
          res.sendFile(mp4);
        })
      }
    } else {
      res.send(404);
    }
  } else {
    res.send(404);
  }
});

app.listen(8000)

console.log('ready');
